### ISSUE TITLE
Cannot run the tests

### ISSUE THREAD

**Issue by carolineschnapp** [saasbook/hw-ruby-intro#19]
I did a `bundle install` to install rspec, but when I try and run the tests, I get an error:

```
user:~/workspace/hw-ruby-intro/spec (master) $ rspec part1_spec.rb 
/home/ubuntu/workspace/hw-ruby-intro/spec/part1_spec.rb:1:in `require': cannot load such file -- ruby_intro.rb (LoadError)
        from /home/ubuntu/workspace/hw-ruby-intro/spec/part1_spec.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by carolineschnapp** [comment]
Nevermind, you cannot run `rspec` from the `spec` folder. 

Here is how I am able to run the tests:

```
user:~/workspace/hw-ruby-intro/spec (master) $ cd ..
user:~/workspace/hw-ruby-intro (master) $ rspec spec/part1_spec.rb
```

I should have done exactly as described in the readme.

Stackoverflow saved me: http://stackoverflow.com/a/28167361
